<?php
session_start();
$plans = require_once '../../server/config/premiumPlan.php'; 
$selected_plan_id = $_GET['plan'] ?? 'pro'; 

if (!array_key_exists($selected_plan_id, $plans)) {
    header('Location: premium.php');
    exit;
}

$selected_plan = $plans[$selected_plan_id];

// Cấu hình ngân hàng cho VietQR
$STK = '1043132503';
$BANK_ID = '970436'; // Vietcombank
$ACCOUNT_NAME = 'PREPHUB TEAM';
$TEMPLATE = 'compact';

// Tạo nội dung chuyển khoản
$transferContent = "PREPHUB " . strtoupper($selected_plan_id) . " " . ($_SESSION['user_id'] ?? 'GUEST');
?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thanh toán - PREPHUB</title>
    <?php include './components/metadata.php'; ?>
    <link rel="stylesheet" href="../styles/payment.css">
    <!-- Lucide Icons -->
    <script src="https://unpkg.com/lucide@latest"></script>
</head>
<body>
    <div class="checkout-page">
        <div class="payment-card">
            <!-- Header -->
            <div class="card-header">
                <h1>Thanh toán gói <?= $selected_plan['name'] ?></h1>
                <a href="premium.php" class="btn-close">
                    <i data-lucide="x"></i>
                </a>
            </div>

            <!-- Body -->
            <div class="card-body">
                <!-- Plan Summary Banner -->
                <div class="plan-banner">
                    <div class="plan-info-item">
                        <label>Gói dịch vụ</label>
                        <span><?= $selected_plan['name'] ?></span>
                    </div>
                    <div class="plan-info-item">
                        <label>Chu kỳ</label>
                        <span><?= $selected_plan['period'] ?></span>
                    </div>
                    <div class="plan-info-item">
                        <label>Tổng thanh toán</label>
                        <span class="price-tag"><?= number_format($selected_plan['price'], 0, ',', '.') ?>₫</span>
                    </div>
                </div>

                <!-- Left: QR Code Section -->
                <div class="payment-section">
                    <div class="section-title">
                        <i data-lucide="qr-code" class="icon-qr"></i>
                        <span>Quét mã QR để thanh toán</span>
                    </div>
                    <div class="qr-container">
                        <div class="qr-frame" id="qr-container">
                            <!-- Image will be generated by JS -->
                            <div class="spinner"></div>
                        </div>
                        <p style="font-size: 13px; color: #64748b; text-align: center;">
                            Sử dụng ứng dụng Ngân hàng hoặc Ví điện tử để quét mã
                        </p>
                    </div>
                </div>

                <!-- Right: Bank Details Section -->
                <div class="payment-section">
                    <div class="section-title">
                        <i data-lucide="credit-card" class="icon-bank"></i>
                        <span>Chuyển khoản thủ công</span>
                    </div>
                    <div class="bank-details">
                        <!-- Ngân hàng -->
                        <div class="detail-row">
                            <div class="detail-label">Ngân hàng</div>
                            <div class="detail-value-wrapper">
                                <span class="detail-value">Vietcombank</span>
                            </div>
                        </div>
                        <!-- Chủ tài khoản -->
                        <div class="detail-row">
                            <div class="detail-label">Chủ tài khoản</div>
                            <div class="detail-value-wrapper">
                                <span class="detail-value"><?= $ACCOUNT_NAME ?></span>
                            </div>
                        </div>
                        <!-- STK -->
                        <div class="detail-row">
                            <div class="detail-label">Số tài khoản</div>
                            <div class="detail-value-wrapper">
                                <span class="detail-value" id="copy-stk"><?= $STK ?></span>
                                <button class="btn-copy" onclick="copyText('<?= $STK ?>', this)">
                                    <i data-lucide="copy" style="width:14px"></i> Copy
                                </button>
                            </div>
                        </div>
                        <!-- Số tiền -->
                        <div class="detail-row">
                            <div class="detail-label">Số tiền</div>
                            <div class="detail-value-wrapper">
                                <span class="detail-value amount" id="copy-amount"><?= number_format($selected_plan['price'], 0, ',', '.') ?>₫</span>
                                <button class="btn-copy" onclick="copyText('<?= $selected_plan['price'] ?>', this)">
                                    <i data-lucide="copy" style="width:14px"></i> Copy
                                </button>
                            </div>
                        </div>
                        <!-- Nội dung -->
                        <div class="detail-row">
                            <div class="detail-label">Nội dung chuyển khoản</div>
                            <div class="detail-value-wrapper" style="flex-direction: column; align-items: flex-start; gap: 8px;">
                                <span class="detail-value" id="copy-content" style="background: #f1f5f9; padding: 8px; border-radius: 6px; width: 100%; box-sizing: border-box; font-size: 14px;"><?= $transferContent ?></span>
                                <button class="btn-copy" onclick="copyText('<?= $transferContent ?>', this)" style="align-self: flex-end;">
                                    <i data-lucide="copy" style="width:14px"></i> Copy
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="instructions">
                        <h4><i data-lucide="info" style="width:14px; vertical-align: middle;"></i> Lưu ý:</h4>
                        <ul>
                            <li>Nội dung chuyển khoản phải chính xác để hệ thống tự động kích hoạt.</li>
                            <li>Giao dịch thường được xử lý trong vòng 1-5 phút.</li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Footer / Verify Button -->
            <div class="card-footer">
                <button class="btn-verify" onclick="simulatePayment()">
                    Tôi đã chuyển khoản
                </button>
                <div class="support-info">
                    Gặp khó khăn? Liên hệ Hotline: <b>1900 8888</b>
                </div>
            </div>
        </div>
    </div>

    <!-- Loading Overlay -->
    <div class="loading-overlay" id="loading-overlay">
        <div id="loading-state">
            <div class="spinner"></div>
            <p id="loading-text">Đang kiểm tra giao dịch...</p>
        </div>
        <div id="success-state" style="display: none; text-align: center;">
            <div class="success-icon"><i data-lucide="check-circle-2" style="width: 80px; height: 80px;"></i></div>
            <h2 style="font-size: 24px; margin-bottom: 8px;">Thanh toán thành công!</h2>
            <p style="opacity: 0.8;">Tài khoản của bạn đã được nâng cấp lên <b><?= $selected_plan['name'] ?></b></p>
        </div>
    </div>

    <script>
        // Khởi tạo Lucide Icons
        lucide.createIcons();

        // Generate VietQR URL
        const BANK_ID = '<?= $BANK_ID ?>';
        const STK = '<?= $STK ?>';
        const AMOUNT = '<?= $selected_plan['price'] ?>';
        const CONTENT = '<?= $transferContent ?>';
        const ACC_NAME = '<?= $ACCOUNT_NAME ?>';
        
        const qrUrl = `https://img.vietqr.io/image/${BANK_ID}-${STK}-compact.png?amount=${AMOUNT}&addInfo=${encodeURIComponent(CONTENT)}&accountName=${encodeURIComponent(ACC_NAME)}`;
        
        const img = new Image();
        img.src = qrUrl;
        img.onload = () => {
            document.getElementById('qr-container').innerHTML = `<img src="${qrUrl}" alt="VietQR">`;
        };

        // Hàm copy text
        function copyText(text, btn) {
            navigator.clipboard.writeText(text).then(() => {
                const originalContent = btn.innerHTML;
                btn.classList.add('copied');
                btn.innerHTML = `<i data-lucide="check" style="width:14px"></i> Đã copy`;
                lucide.createIcons();
                
                setTimeout(() => {
                    btn.classList.remove('copied');
                    btn.innerHTML = originalContent;
                    lucide.createIcons();
                }, 2000);
            });
        }

        // Hàm giả lập thanh toán
        function simulatePayment() {
            const overlay = document.getElementById('loading-overlay');
            const loadingState = document.getElementById('loading-state');
            const successState = document.getElementById('success-state');
            const loadingText = document.getElementById('loading-text');

            overlay.style.display = 'flex';

            // Gửi request tới backend để update session (demo)
            fetch('../../server/controllers/payment-success.php', {
                method: 'POST'
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    // Giả lập thời gian chờ 2.5s cho nó giống thật
                    setTimeout(() => {
                        loadingText.innerText = "Xác nhận thành công!";
                        
                        setTimeout(() => {
                            loadingState.style.display = 'none';
                            successState.style.display = 'block';
                            document.querySelector('.success-icon').style.display = 'block';
                            lucide.createIcons();

                            // Chuyển hướng sau 2 giây
                            setTimeout(() => {
                                window.location.href = 'user.php?upgrade=success';
                            }, 2000);
                        }, 1000);
                    }, 2000);
                }
            })
            .catch(err => {
                console.error(err);
                alert("Có lỗi xảy ra, vui lòng thử lại!");
                overlay.style.display = 'none';
            });
        }
    </script>
</body>
</html>